# Generated by Django 3.2.4 on 2021-07-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='dateOfBirth',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
