# Generated by Django 3.2.4 on 2021-07-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210703_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='dateofbirth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
